version: "3"
services:
  spring-milsestone: 
    image: spring-milestone
    restart: always
    build: .
    ports:
      - 9090:8080
    environment:
       MYSQL_HOST: mysqlamk
       MYSQL_USER: root
       MYSQL_PASSWORD: Elayarani@20
       MYSQL_PORT: 3306
       
  mysqlms: 
    container_name: mysqlms
    image: mysql:5.6
    ports:
      - 3308:3306
    environment:
        MYSQL_DATABASE: msa4
        MYSQL_ROOT_PASSWORD:Elayarani@20
    
